### ISSUE TITLE
Full Screen Spans Across Both Monitors

### ISSUE THREAD

**Issue by Simmonz** [qirien/personal-space#2]
When I choose the full screen option in the options menu it spans the game across both of my two monitors instead of just using the full screen of my primary monitor. I am using version 1.8 on Linux. I have tried on two systems.

Intel I7-4770 |16GB DDR3-2133 CL9 | Intel HD 4600 1536MB | Mesa 20.0.8 | Trisquel 9.0 | Mate 1.20.0 | Kernel 5.10.17-gnu | Acer HA220Q 1920x1080 @ 75hz | HP E221i 1920*1080 @ 60hz

AMD FX-6100 | 16GB DDR3-1600 CL9 | MSI RX 580 8GB Gaming X | Mesa 20.3.4 | Manjaro 20.2.1 | Mate 1.24.1 | Kernel 5.10.15-1-MANJARO | AOC G2460P 1920*1080 @ 144hz | HP E221i 1920*1080 @ 60hz

**Comment by qirien** [comment]
Sorry to hear that! I think that is a Ren'Py bug; our new build was made with a newer version of Ren'Py and might behave better. Will you give it a try? If it still happens, we can report a Ren'Py bug: https://github.com/renpy/renpy/issues
